# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 04:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='static/uploads/%Y/%m/%d/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='static/uploads/%Y/%m/%d/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='static/uploads/%Y/%m/%d/')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=4096)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='test@test.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 11, 14, 4, 1, 8, 667463, tzinfo=utc))),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
                ('img', models.ImageField(blank=True, default=b'static/images/event.jpg', upload_to='static/uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('news', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default=b'static/images/user.svg', null=True, upload_to='static/uploads/%Y/%m/%d/')),
                ('first_name', models.CharField(default='', max_length=256)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('house_number', models.CharField(blank=True, max_length=8, null=True)),
                ('street', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('directory_visible', models.BooleanField(default=False)),
                ('email_list', models.BooleanField(default=False)),
                ('is_president', models.BooleanField(default=False)),
                ('is_vice_president', models.BooleanField(default=False)),
                ('is_secretary', models.BooleanField(default=False)),
                ('is_treasurer', models.BooleanField(default=False)),
                ('is_director', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=32, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=32, null=True)),
                ('next_due_date', models.DateTimeField(blank=True, null=True)),
                ('boat_ramp', models.BooleanField(default=False)),
                ('boat_ramp_next_due_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='saia.Profile'),
        ),
        migrations.AddField(
            model_name='classified',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='saia.Profile'),
        ),
    ]
