# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-31 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 10, 31, 16, 48, 11, 673979, tzinfo=utc))),
                ('description', models.CharField(max_length=1024)),
                ('img', models.ImageField(upload_to='static/uploads/')),
            ],
        ),
    ]
