# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-31 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0002_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(default='New Event', max_length=64),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 16, 59, 24, 716902, tzinfo=utc)),
        ),
    ]
