# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 19:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0003_auto_20171031_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 19, 11, 44, 962301, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='img',
            field=models.ImageField(upload_to='static/uploads/%Y/%m/%d/'),
        ),
    ]
