# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0014_auto_20171102_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 13, 5, 17, 600312, tzinfo=utc)),
        ),
    ]
