# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0015_auto_20171102_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='static/images/user.svg', upload_to='static/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 15, 58, 4, 583407, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
