# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0016_auto_20171102_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 15, 59, 45, 259989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/%Y/%m/%d/'),
        ),
    ]
