# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-02 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0019_auto_20171102_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_officer',
            new_name='is_director',
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 18, 50, 58, 675849, tzinfo=utc)),
        ),
    ]
