# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-03 20:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0020_auto_20171102_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 20, 30, 18, 336911, tzinfo=utc)),
        ),
    ]
