# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-03 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0021_auto_20171103_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_transaction_ids',
            field=models.CharField(default='[]', max_length=8192),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 20, 47, 47, 258293, tzinfo=utc)),
        ),
    ]
