# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-03 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0023_auto_20171103_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='charge_automatically',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_payment',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 20, 57, 3, 986358, tzinfo=utc)),
        ),
    ]
