# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0024_auto_20171103_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='charge_automatically',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_payment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_transaction_ids',
        ),
        migrations.AddField(
            model_name='profile',
            name='boat_ramp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='boat_ramp_next_due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 18, 54, 39, 701944, tzinfo=utc)),
        ),
    ]
