# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0026_auto_20171106_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 22, 6, 46, 109645, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='boat_ramp_next_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='next_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
