# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0027_auto_20171106_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 18, 46, 15, 398633, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='static/images/user.svg', null=True, upload_to='static/uploads/%Y/%m/%d/'),
        ),
    ]
