# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0028_auto_20171107_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 18, 47, 12, 650761, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
