# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 20:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0029_auto_20171107_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img1', models.ImageField(blank=True, default='static/images/classified.jpg', null=True, upload_to='static/uploads/%Y/%m/%d/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='static/uploads/%Y/%m/%d/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='static/uploads/%Y/%m/%d/')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=4096)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saia.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 20, 56, 23, 378328, tzinfo=utc)),
        ),
    ]
