# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0032_auto_20171109_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='saia.Profile'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 10, 16, 50, 25, 26074, tzinfo=utc)),
        ),
    ]
