# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 22:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0034_auto_20171110_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 10, 22, 30, 48, 839282, tzinfo=utc)),
        ),
    ]
