# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-09 03:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('saia', '0002_auto_20190702_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 3, 47, 37, 377358, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='events',
            name='tags',
            field=models.ManyToManyField(to='saia.Tag'),
        ),
    ]
